apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio
  ports:
    - protocol: TCP
      port: 8080        
      targetPort: 80    
  type: NodePort  # Expose via a NodePort for external access
